# Generated by Django 5.0.1 on 2025-05-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Hata ID')),
                ('error_type', models.CharField(choices=[('system', 'Sistem Hatasi'), ('database', 'Veritabani Hatasi'), ('api', 'API Hatasi'), ('automation', 'Otomasyon Hatasi'), ('authentication', 'Kimlik Dogrulama Hatasi'), ('permission', 'Yetki Hatasi'), ('validation', 'Dogrulama Hatasi'), ('network', 'Ag Hatasi'), ('custom', 'Ozel Hata')], max_length=20, verbose_name='Hata Tipi')),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Bilgi'), ('warning', 'Uyari'), ('error', 'Hata'), ('critical', 'Kritik')], max_length=10, verbose_name='Onem Derecesi')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('acknowledged', 'Goruldu'), ('investigating', 'Inceleniyor'), ('resolved', 'Cozuldu'), ('ignored', 'Yoksayildi'), ('recurring', 'Tekrarlayan')], default='new', max_length=20, verbose_name='Durum')),
                ('message', models.TextField(verbose_name='Hata Mesaji')),
                ('exception_type', models.CharField(max_length=200, verbose_name='Istisna Tipi')),
                ('traceback', models.TextField(verbose_name='Hata Izi')),
                ('file_path', models.CharField(max_length=500, verbose_name='Dosya Yolu')),
                ('function_name', models.CharField(max_length=200, verbose_name='Fonksiyon Adi')),
                ('line_number', models.IntegerField(verbose_name='Satir Numarasi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='Kullanici Tarayicisi')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL')),
                ('occurrence_count', models.IntegerField(default=1, verbose_name='Tekrar Sayisi')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Ilk Gorulme')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Son Gorulme')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Cozum Tarihi')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'hata kaydi',
                'verbose_name_plural': 'hata kayitlari',
                'ordering': ['-last_seen'],
            },
        ),
    ]
