# Generated by Django 5.0.1 on 2025-05-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Otomasyon Adi')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Otomasyon Kodu')),
                ('description', models.TextField(verbose_name='Aciklama')),
                ('type', models.CharField(choices=[('api', 'API Tabanli'), ('script', 'Script Tabanli'), ('workflow', 'Is Akisi'), ('integration', 'Entegrasyon'), ('report', 'Rapor')], max_length=20, verbose_name='Otomasyon Tipi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif'), ('development', 'Gelistirme'), ('testing', 'Test')], default='development', max_length=20, verbose_name='Durum')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikon')),
                ('entry_point', models.CharField(max_length=255, verbose_name='Giris Noktasi')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametreler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'otomasyon',
                'verbose_name_plural': 'otomasyonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametreler')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('running', 'Calisiyor'), ('completed', 'Tamamlandi'), ('failed', 'Basarisiz'), ('cancelled', 'Iptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Sonuc')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesaji')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Baslama Zamani')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamani')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='automations.automation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'otomasyon calistirma',
                'verbose_name_plural': 'otomasyon calistirmalari',
                'ordering': ['-started_at'],
            },
        ),
    ]
