# Generated by Django 5.0.1 on 2025-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automation_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='config_template',
            field=models.JSONField(blank=True, default=dict, verbose_name='Konfigurasyon Sablonu'),
        ),
        migrations.AddField(
            model_name='automation',
            name='input_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='Giris Alanlari'),
        ),
        migrations.AddField(
            model_name='automation',
            name='output_format',
            field=models.CharField(default='json', max_length=50, verbose_name='Cikti Formati'),
        ),
        migrations.AddField(
            model_name='automation',
            name='project_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Proje Yolu'),
        ),
        migrations.AddField(
            model_name='automation',
            name='requirements_file',
            field=models.FileField(blank=True, null=True, upload_to='requirements/', verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='automation',
            name='ui_type',
            field=models.CharField(choices=[('form', 'Form'), ('file_upload', 'Dosya Yukleme'), ('wizard', 'Adim Adim'), ('custom', 'Ozel')], default='form', max_length=20, verbose_name='Arayuz Tipi'),
        ),
    ]
