# Generated by Django 5.0.1 on 2025-05-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Widget Adi')),
                ('widget_type', models.CharField(choices=[('text', 'Metin'), ('html', 'HTML'), ('image', 'Resim'), ('button', 'Buton'), ('form', 'Form'), ('card', 'Kart'), ('list', 'Liste'), ('table', 'Tablo'), ('chart', 'Grafik'), ('automation', 'Otomasyon')], max_length=20, verbose_name='Widget Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('configuration', models.JSONField(default=dict, verbose_name='Yapilandirma')),
                ('content', models.TextField(blank=True, verbose_name='Icerik')),
                ('is_global', models.BooleanField(default=False, verbose_name='Global Widget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'widget',
                'verbose_name_plural': 'widgetlar',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sayfa Basligi')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Adi')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinda'), ('archived', 'Arsivlenmis')], default='draft', max_length=20, verbose_name='Durum')),
                ('is_homepage', models.BooleanField(default=False, verbose_name='Ana Sayfa')),
                ('layout', models.JSONField(default=dict, verbose_name='Sayfa Duzeni')),
                ('requires_auth', models.BooleanField(default=False, verbose_name='Kimlik Dogrulama Gerekli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='pages', to='departments.department')),
            ],
            options={
                'verbose_name': 'sayfa',
                'verbose_name_plural': 'sayfalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.JSONField(default=dict, verbose_name='Konum')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sira')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_widgets', to='page_builder.page')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_widgets', to='page_builder.widget')),
            ],
            options={
                'verbose_name': 'sayfa widget',
                'verbose_name_plural': 'sayfa widgetlari',
                'ordering': ['page', 'order'],
            },
        ),
    ]
