# Generated by Django 5.0.1 on 2025-05-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Departman Adi')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Departman Kodu')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme Tarihi')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='departments.department')),
            ],
            options={
                'verbose_name': 'departman',
                'verbose_name_plural': 'departmanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ana Departman')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='Katilim Tarihi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'departman uyesi',
                'verbose_name_plural': 'departman uyeleri',
                'unique_together': {('department', 'user')},
            },
        ),
    ]
